spring:
  application:
    name: mybatis

  datasource:
    hikari:
      auto-commit: false
      minimum-idle: 10
      maximum-pool-size: 60
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select 1
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bta60gdlctrans1?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root


mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.ecidi.cim.megagame.mega.details

server:
  port: 8091